---

include:
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.3.3
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.0.2
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.2
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.3.0
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: jfrog-cli
  DOCKER_DISABLE_ALL_JOBS: 'true'
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

public:1.47.2:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg JFROG_CLI_VERSION=1.47.2
    TAG: 1.47.2

public:1.39.3:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg JFROG_CLI_VERSION=1.39.3
    TAG: 1.39.3
...
