---
stages:
  - lint
  - build
  - publish
  - release

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.0.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.2.2
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 2.10.0
    file: gitlab-ci.yml

variables:
  APP_NAME: jfrog-cli
  DOCKER_DISABLE_ALL_JOBS: 'true'
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

public:1.38.2:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg JFROG_CLI_VERSION=1.38.2
    TAG: 1.38.2
...
